//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.MSBuildTask")]
[assembly: AssemblyDescription("Cake MSBuildTask AddIn")]
[assembly: AssemblyCompany("Mark Walker")]
[assembly: AssemblyProduct("Cake.MSBuildTask")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyCopyright("Copyright © Mark Walker 2015")]
[assembly: CLSCompliant(true)]

